name: "WiFi and BLE beacon server"
description: "Bachelor project of Jan Stark"
version: "0.0.5"
slug: "wifi_ble_beacon"
# Allow access to the internal authentication api for the basic http auth
auth_api: true
# Allow access to the internal api for creation and updating of entities
homeassistant_api: true
# Map config folder for easy log access
map: 
  - config:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8000/tcp: 8000
startup: application
options:
  # String of the SSID the controllers will be searching for
  ssid: "wifi ssid"
  # List of MAC-Addresses that are tracked, default=all
  wifi_filter: 
  ble_filter: 
  # Amount of seconds after which a signal of lower RSSI can overwrite an existing one that had a higher RSSI
  overwrite_threshold: 5
  away_timer: 60
  verbose_logging: false
schema:
  ssid: str
  # limit input to a comma-seperated list of MAC-addresses
  wifi_filter: match(^([0-9a-fA-F]{2}[:-]){5}[0-9a-fA-F]{2}(,([0-9a-fA-F]{2}[:-]){5}[0-9a-fA-F]{2})*$)?
  ble_filter: match(^([0-9a-fA-F]{2}[:-]){5}[0-9a-fA-F]{2}(,([0-9a-fA-F]{2}[:-]){5}[0-9a-fA-F]{2})*$)?
  # limit the overwrite threshold to the range between 1 seconds and 5 minutes
  overwrite_threshold: int(1,300)
  away_timer: int(1,600)
  verbose_logging: bool